Created flightComputer.cpp, readme.md, and staticVariables.h
USSTR-Avionics/Achilles pull request #4
Opened 2023-05-28 17:05 UTC by EricC1231

-created most of the functions that are needed for the flight computer and created the base state machine
 -populated the enum flightStates variable for the state machine
the main purpose of this is just to get set up for populating the functions and have everyone on the same page as to how the flight computer program is going to be set up.

2023-05-28 21:00 UTC, frroossst requested changes

2023-05-28 21:00 UTC, frroossst commented on Software/flight_computer_program/src/StaticVariables.h
> +bool PASSED = true;
why do you have two separate variables to represent a boolean state?

just have, `tests_pass = bool`, it doesn't make sense for two vars to represent the same boolean state

2023-05-28 21:00 UTC, frroossst commented on Software/flight_computer_program/src/FlightComputer.cpp
> +bool HealthCheck(){
please just do snake case or camel case, Pascal case would be a good fit for something like a class name, a common way of defining functions and classes is if they start with a lower case they're private, if they're upper case they're public, this gives a very quick visual indication of the scope of the function.

2023-05-28 21:00 UTC, frroossst commented on Software/flight_computer_program/src/FlightComputer.cpp
> +        break;
you default case should go into a mode where you make sure your parachute deploys, else you're stuck in one state

2023-05-28 21:00 UTC, frroossst commented on Software/flight_computer_program/src/FlightComputer.cpp
> +FlightStates FlightState = UNARMED;
don't do shared mutable state if you're doing OOP, just make it a class

2023-05-28 21:00 UTC, frroossst commented on Software/flight_computer_program/src/FlightComputer.cpp
> +FlightStates FlightState = UNARMED;
Speaking of which, all of this should just be a class, the whole statemachine

2023-05-29 10:28 UTC, bristine02 commented
Hey @EricC1231  I just switched the project from pio to Cube IDE and added FreeRTOS. The folder structure is completely different now so your changes can't be merged right now. 
As we agreed, we're using classes for almost everything so it makes sense to make the flight computer a class too as Adhyan commented above. 
Because the project is very different now, you'll have to do:
1. Update your fork
2. Update your local repo or just clone it again (recommended)
3. Add your code as a class in the Software/Core. You'll see an empty class for the builtin led which I added.
4. Commit, push, then we can merge

2023-05-29 13:06 UTC, EricC1231 commented
OK, I've been working on throwing everything into classes so I'll soon have everything ready to commit.

2023-05-29 14:47 UTC, frroossst commented
Don't re clone you can just
`git fetch upstream master`  
`git pull upstream master`  
`git pull --force`

2023-05-29 23:33 UTC, closed without merging